### ISSUE TITLE
Component: Date picker

### ISSUE THREAD

**Issue by daniknewgarden** [EXO-UI/exo-ui#58]
# TODO: write description
# Context:

- Point 1.

# Design:

## Links:

[<img src="https://www.bynder.com/images/meta/meta-figma.jpg" width="100">](LINK)

# Acceptance criteria:

- [ ] The new `Component` component is created.
- [ ] It accepts the following props:
  - [ ] Prop 1.
- [ ] It is documented.
  - [ ] In storybook.
  - [ ] By writing unit tests.
